# Generated by Django 4.2.4 on 2023-08-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='topics/images'),
        ),
    ]
