# Generated by Django 4.2.4 on 2023-08-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.IntegerField(default=10)),
                ('absent', models.BooleanField(default=True)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
    ]
