# Generated by Django 4.2.4 on 2023-08-10 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_alter_track_description_alter_track_image'),
        ('students', '0004_student_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='tracks.track'),
        ),
    ]
