# Generated by Django 4.2.4 on 2023-08-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tracks/images'),
        ),
    ]
